-- lvim-tex.conceal.data: the SHIPPED character maps the conceal renderer looks commands up in.
--
-- Data only — no logic, no requires. It lives apart from `lvim-tex.conceal` because it is bulk: the
-- renderer is a page of code, the maps are a thousand glyphs, and mixing them makes neither readable.
--
-- Every table here is user-mergeable: `conceal.maps.<group>` in the live config is merged OVER a COPY
-- of these (lvim-tex.conceal `refresh()`), so a user entry for the same command replaces the shipped
-- one and an unmentioned command keeps its shipped glyph. Nothing in this file is ever mutated.
--
-- Three value SHAPES exist, and which one a group uses is fixed by the group:
--   • string          — the replacement character (`math_symbols`, `delimiters`, `refs`, `sections`).
--                       The empty string means "hide it entirely", which is how `\left` / `\right` and
--                       the sized modifiers disappear while the delimiter they size stays.
--   • letter table    — base letter → the PRECOMPOSED glyph (`accents`, and the maths alphabets in
--                       `styles`). Only single-letter arguments are concealed, and only where a real
--                       codepoint exists: there is no `\vec` table because Unicode has no precomposed
--                       "letter with arrow above", and inventing one with a combining mark would
--                       change the cell count of the line.
--   • highlight group — `styles` entries whose value is a string: the wrapper (`\textbf{` … `}`) is
--                       hidden and the ARGUMENT is highlighted instead, because conceal can replace a
--                       range with one character but cannot make text bold.
--
-- The greek/operator/relation/arrow sets are the ones a maths document actually uses; the accent
-- tables carry only combinations Unicode precomposes (an `\'{q}` stays `\'{q}`).
--
---@module "lvim-tex.conceal.data"

local M = {}

--- A COPY of `t`, so two commands can share a letter table in this file without a user override of
--- one of them silently rewriting the other (the merge in `conceal.refresh()` writes in place).
---@param t table<string, string>
---@return table<string, string>
local function copy(t)
    local out = {}
    for k, v in pairs(t) do
        out[k] = v
    end
    return out
end

-- ---------------------------------------------------------------------------
-- math_symbols — bare commands that ARE a character. Concealed inside maths only.
-- ---------------------------------------------------------------------------

---@type table<string, string>
M.math_symbols = {
    -- Greek, lower case (including the `var` shapes, which are distinct codepoints).
    ["\\alpha"] = "α",
    ["\\beta"] = "β",
    ["\\gamma"] = "γ",
    ["\\delta"] = "δ",
    ["\\epsilon"] = "ϵ",
    ["\\varepsilon"] = "ε",
    ["\\zeta"] = "ζ",
    ["\\eta"] = "η",
    ["\\theta"] = "θ",
    ["\\vartheta"] = "ϑ",
    ["\\iota"] = "ι",
    ["\\kappa"] = "κ",
    ["\\lambda"] = "λ",
    ["\\mu"] = "μ",
    ["\\nu"] = "ν",
    ["\\xi"] = "ξ",
    ["\\pi"] = "π",
    ["\\varpi"] = "ϖ",
    ["\\rho"] = "ρ",
    ["\\varrho"] = "ϱ",
    ["\\sigma"] = "σ",
    ["\\varsigma"] = "ς",
    ["\\tau"] = "τ",
    ["\\upsilon"] = "υ",
    ["\\phi"] = "ϕ",
    ["\\varphi"] = "φ",
    ["\\chi"] = "χ",
    ["\\psi"] = "ψ",
    ["\\omega"] = "ω",

    -- Greek, upper case.
    ["\\Gamma"] = "Γ",
    ["\\Delta"] = "Δ",
    ["\\Theta"] = "Θ",
    ["\\Lambda"] = "Λ",
    ["\\Xi"] = "Ξ",
    ["\\Pi"] = "Π",
    ["\\Sigma"] = "Σ",
    ["\\Upsilon"] = "Υ",
    ["\\Phi"] = "Φ",
    ["\\Psi"] = "Ψ",
    ["\\Omega"] = "Ω",

    -- Big operators.
    ["\\sum"] = "∑",
    ["\\prod"] = "∏",
    ["\\coprod"] = "∐",
    ["\\int"] = "∫",
    ["\\iint"] = "∬",
    ["\\iiint"] = "∭",
    ["\\oint"] = "∮",
    ["\\bigcup"] = "⋃",
    ["\\bigcap"] = "⋂",
    ["\\bigvee"] = "⋁",
    ["\\bigwedge"] = "⋀",
    ["\\bigoplus"] = "⨁",
    ["\\bigotimes"] = "⨂",
    ["\\bigodot"] = "⨀",
    ["\\biguplus"] = "⨄",
    ["\\bigsqcup"] = "⨆",

    -- Binary operators.
    ["\\pm"] = "±",
    ["\\mp"] = "∓",
    ["\\times"] = "×",
    ["\\div"] = "÷",
    ["\\cdot"] = "⋅",
    ["\\ast"] = "∗",
    ["\\star"] = "⋆",
    ["\\circ"] = "∘",
    ["\\bullet"] = "∙",
    ["\\oplus"] = "⊕",
    ["\\ominus"] = "⊖",
    ["\\otimes"] = "⊗",
    ["\\oslash"] = "⊘",
    ["\\odot"] = "⊙",
    ["\\dagger"] = "†",
    ["\\ddagger"] = "‡",
    ["\\amalg"] = "⨿",
    ["\\cap"] = "∩",
    ["\\cup"] = "∪",
    ["\\uplus"] = "⊎",
    ["\\sqcap"] = "⊓",
    ["\\sqcup"] = "⊔",
    ["\\vee"] = "∨",
    ["\\wedge"] = "∧",
    ["\\setminus"] = "∖",
    ["\\wr"] = "≀",
    ["\\diamond"] = "⋄",
    ["\\bigtriangleup"] = "△",
    ["\\bigtriangledown"] = "▽",
    ["\\triangleleft"] = "◁",
    ["\\triangleright"] = "▷",

    -- Relations.
    ["\\le"] = "≤",
    ["\\leq"] = "≤",
    ["\\ge"] = "≥",
    ["\\geq"] = "≥",
    ["\\ne"] = "≠",
    ["\\neq"] = "≠",
    ["\\equiv"] = "≡",
    ["\\sim"] = "∼",
    ["\\simeq"] = "≃",
    ["\\approx"] = "≈",
    ["\\cong"] = "≅",
    ["\\propto"] = "∝",
    ["\\prec"] = "≺",
    ["\\succ"] = "≻",
    ["\\preceq"] = "⪯",
    ["\\succeq"] = "⪰",
    ["\\ll"] = "≪",
    ["\\gg"] = "≫",
    ["\\subset"] = "⊂",
    ["\\supset"] = "⊃",
    ["\\subseteq"] = "⊆",
    ["\\supseteq"] = "⊇",
    ["\\sqsubseteq"] = "⊑",
    ["\\sqsupseteq"] = "⊒",
    ["\\in"] = "∈",
    ["\\ni"] = "∋",
    ["\\notin"] = "∉",
    ["\\vdash"] = "⊢",
    ["\\dashv"] = "⊣",
    ["\\models"] = "⊨",
    ["\\perp"] = "⊥",
    ["\\mid"] = "∣",
    ["\\parallel"] = "∥",
    ["\\asymp"] = "≍",
    ["\\doteq"] = "≐",
    ["\\bowtie"] = "⋈",
    ["\\smile"] = "⌣",
    ["\\frown"] = "⌢",
    ["\\nless"] = "≮",
    ["\\ngtr"] = "≯",
    ["\\nleq"] = "≰",
    ["\\ngeq"] = "≱",
    ["\\nsubseteq"] = "⊈",
    ["\\nsupseteq"] = "⊉",

    -- Arrows.
    ["\\gets"] = "←",
    ["\\leftarrow"] = "←",
    ["\\to"] = "→",
    ["\\rightarrow"] = "→",
    ["\\leftrightarrow"] = "↔",
    ["\\Leftarrow"] = "⇐",
    ["\\Rightarrow"] = "⇒",
    ["\\Leftrightarrow"] = "⇔",
    ["\\implies"] = "⇒",
    ["\\impliedby"] = "⇐",
    ["\\iff"] = "⇔",
    ["\\mapsto"] = "↦",
    ["\\longmapsto"] = "⟼",
    ["\\longleftarrow"] = "⟵",
    ["\\longrightarrow"] = "⟶",
    ["\\longleftrightarrow"] = "⟷",
    ["\\Longleftarrow"] = "⟸",
    ["\\Longrightarrow"] = "⟹",
    ["\\Longleftrightarrow"] = "⟺",
    ["\\uparrow"] = "↑",
    ["\\downarrow"] = "↓",
    ["\\updownarrow"] = "↕",
    ["\\Uparrow"] = "⇑",
    ["\\Downarrow"] = "⇓",
    ["\\nearrow"] = "↗",
    ["\\searrow"] = "↘",
    ["\\swarrow"] = "↙",
    ["\\nwarrow"] = "↖",
    ["\\hookleftarrow"] = "↩",
    ["\\hookrightarrow"] = "↪",
    ["\\leftharpoonup"] = "↼",
    ["\\leftharpoondown"] = "↽",
    ["\\rightharpoonup"] = "⇀",
    ["\\rightharpoondown"] = "⇁",
    ["\\rightleftharpoons"] = "⇌",

    -- Everything else a maths document reaches for.
    ["\\infty"] = "∞",
    ["\\partial"] = "∂",
    ["\\nabla"] = "∇",
    ["\\forall"] = "∀",
    ["\\exists"] = "∃",
    ["\\nexists"] = "∄",
    ["\\emptyset"] = "∅",
    ["\\varnothing"] = "∅",
    ["\\neg"] = "¬",
    ["\\lnot"] = "¬",
    ["\\not"] = "¬",
    ["\\top"] = "⊤",
    ["\\bot"] = "⊥",
    ["\\angle"] = "∠",
    ["\\triangle"] = "△",
    ["\\surd"] = "√",
    ["\\prime"] = "′",
    ["\\ell"] = "ℓ",
    ["\\hbar"] = "ℏ",
    ["\\imath"] = "ı",
    ["\\jmath"] = "ȷ",
    ["\\aleph"] = "ℵ",
    ["\\wp"] = "℘",
    ["\\Re"] = "ℜ",
    ["\\Im"] = "ℑ",
    ["\\flat"] = "♭",
    ["\\natural"] = "♮",
    ["\\sharp"] = "♯",
    ["\\clubsuit"] = "♣",
    ["\\diamondsuit"] = "♦",
    ["\\heartsuit"] = "♥",
    ["\\spadesuit"] = "♠",
    ["\\dots"] = "…",
    ["\\ldots"] = "…",
    ["\\cdots"] = "⋯",
    ["\\vdots"] = "⋮",
    ["\\ddots"] = "⋱",
    ["\\therefore"] = "∴",
    ["\\because"] = "∵",
    ["\\square"] = "□",
    ["\\blacksquare"] = "■",
    ["\\degree"] = "°",
}

-- ---------------------------------------------------------------------------
-- delimiters — the sizing commands (hidden) and the named delimiters (glyphs).
-- ---------------------------------------------------------------------------
-- The sizing modifiers conceal to NOTHING: `\left(` should read as `(`, not as a
-- character standing in for "left". The delimiter itself is a separate lookup, which is
-- why `\left\langle x \right\rangle` collapses all the way down to `⟨x⟩`.

---@type table<string, string>
M.delimiters = {
    ["\\left"] = "",
    ["\\right"] = "",
    ["\\middle"] = "",
    ["\\big"] = "",
    ["\\Big"] = "",
    ["\\bigg"] = "",
    ["\\Bigg"] = "",
    ["\\bigl"] = "",
    ["\\bigr"] = "",
    ["\\bigm"] = "",
    ["\\Bigl"] = "",
    ["\\Bigr"] = "",
    ["\\Bigm"] = "",
    ["\\biggl"] = "",
    ["\\biggr"] = "",
    ["\\biggm"] = "",
    ["\\Biggl"] = "",
    ["\\Biggr"] = "",
    ["\\Biggm"] = "",

    ["\\langle"] = "⟨",
    ["\\rangle"] = "⟩",
    ["\\lceil"] = "⌈",
    ["\\rceil"] = "⌉",
    ["\\lfloor"] = "⌊",
    ["\\rfloor"] = "⌋",
    ["\\lgroup"] = "⟮",
    ["\\rgroup"] = "⟯",
    ["\\ulcorner"] = "⌜",
    ["\\urcorner"] = "⌝",
    ["\\llcorner"] = "⌞",
    ["\\lrcorner"] = "⌟",
    ["\\lbrace"] = "{",
    ["\\rbrace"] = "}",
    ["\\lbrack"] = "[",
    ["\\rbrack"] = "]",
    ["\\vert"] = "|",
    ["\\lvert"] = "|",
    ["\\rvert"] = "|",
    ["\\Vert"] = "‖",
    ["\\lVert"] = "‖",
    ["\\rVert"] = "‖",
    ["\\{"] = "{",
    ["\\}"] = "}",
    ["\\|"] = "‖",
}

-- ---------------------------------------------------------------------------
-- scripts — `^` / `_` and their contents.
-- ---------------------------------------------------------------------------
-- A script is concealed ONLY when every character of its content has a Unicode script
-- form: `x^{2n}` becomes `x²ⁿ`, `x^{2q}` is left alone, because half-lowered text is
-- worse than none. Unicode has no superscript `q` and no subscript `b`, `c`, `d`, `f`,
-- `g`, `w`, `y`, `z` — the gaps below are Unicode's, not omissions.

---@type table<string, table<string, string>>
M.scripts = {
    superscript = {
        ["0"] = "⁰",
        ["1"] = "¹",
        ["2"] = "²",
        ["3"] = "³",
        ["4"] = "⁴",
        ["5"] = "⁵",
        ["6"] = "⁶",
        ["7"] = "⁷",
        ["8"] = "⁸",
        ["9"] = "⁹",
        ["+"] = "⁺",
        ["-"] = "⁻",
        ["="] = "⁼",
        ["("] = "⁽",
        [")"] = "⁾",
        ["a"] = "ᵃ",
        ["b"] = "ᵇ",
        ["c"] = "ᶜ",
        ["d"] = "ᵈ",
        ["e"] = "ᵉ",
        ["f"] = "ᶠ",
        ["g"] = "ᵍ",
        ["h"] = "ʰ",
        ["i"] = "ⁱ",
        ["j"] = "ʲ",
        ["k"] = "ᵏ",
        ["l"] = "ˡ",
        ["m"] = "ᵐ",
        ["n"] = "ⁿ",
        ["o"] = "ᵒ",
        ["p"] = "ᵖ",
        ["r"] = "ʳ",
        ["s"] = "ˢ",
        ["t"] = "ᵗ",
        ["u"] = "ᵘ",
        ["v"] = "ᵛ",
        ["w"] = "ʷ",
        ["x"] = "ˣ",
        ["y"] = "ʸ",
        ["z"] = "ᶻ",
        ["A"] = "ᴬ",
        ["B"] = "ᴮ",
        ["D"] = "ᴰ",
        ["E"] = "ᴱ",
        ["G"] = "ᴳ",
        ["H"] = "ᴴ",
        ["I"] = "ᴵ",
        ["J"] = "ᴶ",
        ["K"] = "ᴷ",
        ["L"] = "ᴸ",
        ["M"] = "ᴹ",
        ["N"] = "ᴺ",
        ["O"] = "ᴼ",
        ["P"] = "ᴾ",
        ["R"] = "ᴿ",
        ["T"] = "ᵀ",
        ["U"] = "ᵁ",
        ["V"] = "ⱽ",
        ["W"] = "ᵂ",
    },
    subscript = {
        ["0"] = "₀",
        ["1"] = "₁",
        ["2"] = "₂",
        ["3"] = "₃",
        ["4"] = "₄",
        ["5"] = "₅",
        ["6"] = "₆",
        ["7"] = "₇",
        ["8"] = "₈",
        ["9"] = "₉",
        ["+"] = "₊",
        ["-"] = "₋",
        ["="] = "₌",
        ["("] = "₍",
        [")"] = "₎",
        ["a"] = "ₐ",
        ["e"] = "ₑ",
        ["h"] = "ₕ",
        ["i"] = "ᵢ",
        ["j"] = "ⱼ",
        ["k"] = "ₖ",
        ["l"] = "ₗ",
        ["m"] = "ₘ",
        ["n"] = "ₙ",
        ["o"] = "ₒ",
        ["p"] = "ₚ",
        ["r"] = "ᵣ",
        ["s"] = "ₛ",
        ["t"] = "ₜ",
        ["u"] = "ᵤ",
        ["v"] = "ᵥ",
        ["x"] = "ₓ",
    },
}

-- ---------------------------------------------------------------------------
-- accents — command + one letter → the precomposed glyph.
-- ---------------------------------------------------------------------------

local ACUTE = {
    a = "á",
    e = "é",
    i = "í",
    o = "ó",
    u = "ú",
    y = "ý",
    c = "ć",
    g = "ǵ",
    l = "ĺ",
    n = "ń",
    r = "ŕ",
    s = "ś",
    z = "ź",
    A = "Á",
    E = "É",
    I = "Í",
    O = "Ó",
    U = "Ú",
    Y = "Ý",
    C = "Ć",
    L = "Ĺ",
    N = "Ń",
    R = "Ŕ",
    S = "Ś",
    Z = "Ź",
}

local GRAVE = {
    a = "à",
    e = "è",
    i = "ì",
    o = "ò",
    u = "ù",
    n = "ǹ",
    y = "ỳ",
    A = "À",
    E = "È",
    I = "Ì",
    O = "Ò",
    U = "Ù",
    N = "Ǹ",
}

local CIRCUMFLEX = {
    a = "â",
    e = "ê",
    i = "î",
    o = "ô",
    u = "û",
    c = "ĉ",
    g = "ĝ",
    h = "ĥ",
    j = "ĵ",
    s = "ŝ",
    w = "ŵ",
    y = "ŷ",
    z = "ẑ",
    A = "Â",
    E = "Ê",
    I = "Î",
    O = "Ô",
    U = "Û",
    C = "Ĉ",
    G = "Ĝ",
    H = "Ĥ",
    J = "Ĵ",
    S = "Ŝ",
    W = "Ŵ",
    Y = "Ŷ",
}

local DIAERESIS = {
    a = "ä",
    e = "ë",
    i = "ï",
    o = "ö",
    u = "ü",
    y = "ÿ",
    A = "Ä",
    E = "Ë",
    I = "Ï",
    O = "Ö",
    U = "Ü",
    Y = "Ÿ",
}

local TILDE = {
    a = "ã",
    e = "ẽ",
    i = "ĩ",
    n = "ñ",
    o = "õ",
    u = "ũ",
    y = "ỹ",
    A = "Ã",
    E = "Ẽ",
    I = "Ĩ",
    N = "Ñ",
    O = "Õ",
    U = "Ũ",
}

local MACRON = {
    a = "ā",
    e = "ē",
    i = "ī",
    o = "ō",
    u = "ū",
    y = "ȳ",
    A = "Ā",
    E = "Ē",
    I = "Ī",
    O = "Ō",
    U = "Ū",
}

local DOT_ABOVE = {
    a = "ȧ",
    c = "ċ",
    e = "ė",
    g = "ġ",
    o = "ȯ",
    z = "ż",
    A = "Ȧ",
    C = "Ċ",
    E = "Ė",
    G = "Ġ",
    I = "İ",
    O = "Ȯ",
    Z = "Ż",
}

local BREVE = {
    a = "ă",
    e = "ĕ",
    g = "ğ",
    i = "ĭ",
    o = "ŏ",
    u = "ŭ",
    A = "Ă",
    E = "Ĕ",
    G = "Ğ",
    I = "Ĭ",
    O = "Ŏ",
    U = "Ŭ",
}

local CARON = {
    c = "č",
    d = "ď",
    e = "ě",
    g = "ǧ",
    l = "ľ",
    n = "ň",
    r = "ř",
    s = "š",
    t = "ť",
    z = "ž",
    C = "Č",
    D = "Ď",
    E = "Ě",
    G = "Ǧ",
    L = "Ľ",
    N = "Ň",
    R = "Ř",
    S = "Š",
    T = "Ť",
    Z = "Ž",
}

local RING = { a = "å", u = "ů", A = "Å", U = "Ů" }

local DOUBLE_ACUTE = { o = "ő", u = "ű", O = "Ő", U = "Ű" }

local CEDILLA = {
    c = "ç",
    g = "ģ",
    k = "ķ",
    l = "ļ",
    n = "ņ",
    r = "ŗ",
    s = "ş",
    t = "ţ",
    C = "Ç",
    G = "Ģ",
    K = "Ķ",
    L = "Ļ",
    N = "Ņ",
    R = "Ŗ",
    S = "Ş",
    T = "Ţ",
}

local OGONEK = { a = "ą", e = "ę", i = "į", u = "ų", A = "Ą", E = "Ę", I = "Į", U = "Ų" }

-- The text-mode accent commands and their maths-mode synonyms name the same glyphs, so each entry
-- gets its OWN copy of the table (see `copy` above).
---@type table<string, table<string, string>>
M.accents = {
    ["\\'"] = copy(ACUTE),
    ["\\`"] = copy(GRAVE),
    ["\\^"] = copy(CIRCUMFLEX),
    ['\\"'] = copy(DIAERESIS),
    ["\\~"] = copy(TILDE),
    ["\\="] = copy(MACRON),
    ["\\."] = copy(DOT_ABOVE),
    ["\\u"] = copy(BREVE),
    ["\\v"] = copy(CARON),
    ["\\r"] = copy(RING),
    ["\\H"] = copy(DOUBLE_ACUTE),
    ["\\c"] = copy(CEDILLA),
    ["\\k"] = copy(OGONEK),

    ["\\acute"] = copy(ACUTE),
    ["\\grave"] = copy(GRAVE),
    ["\\hat"] = copy(CIRCUMFLEX),
    ["\\widehat"] = copy(CIRCUMFLEX),
    ["\\ddot"] = copy(DIAERESIS),
    ["\\tilde"] = copy(TILDE),
    ["\\widetilde"] = copy(TILDE),
    ["\\bar"] = copy(MACRON),
    ["\\overline"] = copy(MACRON),
    ["\\dot"] = copy(DOT_ABOVE),
    ["\\breve"] = copy(BREVE),
    ["\\check"] = copy(CARON),
    ["\\mathring"] = copy(RING),
}

-- ---------------------------------------------------------------------------
-- styles — a wrapper whose ARGUMENT is what matters.
-- ---------------------------------------------------------------------------
-- A highlight-group value hides `\cmd{` and `}` and paints the argument instead (conceal
-- can replace a range with a character, never with bold text). A letter table is the
-- maths alphabets: a one-letter argument becomes the single codepoint that IS that
-- letter in that alphabet.

---@type table<string, string|table<string, string>>
M.styles = {
    ["\\textbf"] = "@markup.strong",
    ["\\mathbf"] = "@markup.strong",
    ["\\boldsymbol"] = "@markup.strong",
    ["\\textit"] = "@markup.italic",
    ["\\mathit"] = "@markup.italic",
    ["\\emph"] = "@markup.italic",
    ["\\texttt"] = "@markup.raw",
    ["\\mathtt"] = "@markup.raw",
    ["\\underline"] = "@markup.underline",

    ["\\mathbb"] = {
        A = "𝔸",
        B = "𝔹",
        C = "ℂ",
        D = "𝔻",
        E = "𝔼",
        F = "𝔽",
        G = "𝔾",
        H = "ℍ",
        I = "𝕀",
        J = "𝕁",
        K = "𝕂",
        L = "𝕃",
        M = "𝕄",
        N = "ℕ",
        O = "𝕆",
        P = "ℙ",
        Q = "ℚ",
        R = "ℝ",
        S = "𝕊",
        T = "𝕋",
        U = "𝕌",
        V = "𝕍",
        W = "𝕎",
        X = "𝕏",
        Y = "𝕐",
        Z = "ℤ",
        a = "𝕒",
        b = "𝕓",
        c = "𝕔",
        d = "𝕕",
        e = "𝕖",
        f = "𝕗",
        g = "𝕘",
        h = "𝕙",
        i = "𝕚",
        j = "𝕛",
        k = "𝕜",
        l = "𝕝",
        m = "𝕞",
        n = "𝕟",
        o = "𝕠",
        p = "𝕡",
        q = "𝕢",
        r = "𝕣",
        s = "𝕤",
        t = "𝕥",
        u = "𝕦",
        v = "𝕧",
        w = "𝕨",
        x = "𝕩",
        y = "𝕪",
        z = "𝕫",
    },
    ["\\mathcal"] = {
        A = "𝒜",
        B = "ℬ",
        C = "𝒞",
        D = "𝒟",
        E = "ℰ",
        F = "ℱ",
        G = "𝒢",
        H = "ℋ",
        I = "ℐ",
        J = "𝒥",
        K = "𝒦",
        L = "ℒ",
        M = "ℳ",
        N = "𝒩",
        O = "𝒪",
        P = "𝒫",
        Q = "𝒬",
        R = "ℛ",
        S = "𝒮",
        T = "𝒯",
        U = "𝒰",
        V = "𝒱",
        W = "𝒲",
        X = "𝒳",
        Y = "𝒴",
        Z = "𝒵",
        a = "𝒶",
        b = "𝒷",
        c = "𝒸",
        d = "𝒹",
        e = "ℯ",
        f = "𝒻",
        g = "ℊ",
        h = "𝒽",
        i = "𝒾",
        j = "𝒿",
        k = "𝓀",
        l = "𝓁",
        m = "𝓂",
        n = "𝓃",
        o = "ℴ",
        p = "𝓅",
        q = "𝓆",
        r = "𝓇",
        s = "𝓈",
        t = "𝓉",
        u = "𝓊",
        v = "𝓋",
        w = "𝓌",
        x = "𝓍",
        y = "𝓎",
        z = "𝓏",
    },
    ["\\mathfrak"] = {
        A = "𝔄",
        B = "𝔅",
        C = "ℭ",
        D = "𝔇",
        E = "𝔈",
        F = "𝔉",
        G = "𝔊",
        H = "ℌ",
        I = "ℑ",
        J = "𝔍",
        K = "𝔎",
        L = "𝔏",
        M = "𝔐",
        N = "𝔑",
        O = "𝔒",
        P = "𝔓",
        Q = "𝔔",
        R = "ℜ",
        S = "𝔖",
        T = "𝔗",
        U = "𝔘",
        V = "𝔙",
        W = "𝔚",
        X = "𝔛",
        Y = "𝔜",
        Z = "ℨ",
        a = "𝔞",
        b = "𝔟",
        c = "𝔠",
        d = "𝔡",
        e = "𝔢",
        f = "𝔣",
        g = "𝔤",
        h = "𝔥",
        i = "𝔦",
        j = "𝔧",
        k = "𝔨",
        l = "𝔩",
        m = "𝔪",
        n = "𝔫",
        o = "𝔬",
        p = "𝔭",
        q = "𝔮",
        r = "𝔯",
        s = "𝔰",
        t = "𝔱",
        u = "𝔲",
        v = "𝔳",
        w = "𝔴",
        x = "𝔵",
        y = "𝔶",
        z = "𝔷",
    },
}

-- ---------------------------------------------------------------------------
-- refs — a reference is a MARKER plus a key.
-- ---------------------------------------------------------------------------
-- The command becomes one glyph and the braces disappear, so `\autoref{sec:intro}`
-- reads as `󰓹sec:intro`: the key stays legible (it is what the author needs) and the
-- ceremony around it does not. `\label` is deliberately NOT here — a definition should
-- not look like a use; add it in `conceal.maps.refs` if you disagree.

---@type table<string, string>
M.refs = {
    ["\\ref"] = "󰓹",
    ["\\cref"] = "󰓹",
    ["\\Cref"] = "󰓹",
    ["\\autoref"] = "󰓹",
    ["\\eqref"] = "󰓹",
    ["\\pageref"] = "󰓹",
    ["\\vref"] = "󰓹",
    ["\\nameref"] = "󰓹",
    ["\\gls"] = "󰓹",
    ["\\Gls"] = "󰓹",
    ["\\glsplural"] = "󰓹",
    ["\\acrshort"] = "󰓹",
    ["\\acrlong"] = "󰓹",
    ["\\acrfull"] = "󰓹",

    ["\\cite"] = "󰧮",
    ["\\citep"] = "󰧮",
    ["\\citet"] = "󰧮",
    ["\\citeal"] = "󰧮",
    ["\\citeauthor"] = "󰧮",
    ["\\citeyear"] = "󰧮",
    ["\\citeyearpar"] = "󰧮",
    ["\\parencite"] = "󰧮",
    ["\\textcite"] = "󰧮",
    ["\\footcite"] = "󰧮",
    ["\\autocite"] = "󰧮",
    ["\\fullcite"] = "󰧮",
    ["\\nocite"] = "󰧮",
}

-- ---------------------------------------------------------------------------
-- sections — the heading commands (group OFF by default).
-- ---------------------------------------------------------------------------
-- Same shape as refs: the command becomes a glyph, the braces go, the title stays. One
-- glyph for every level by default because the INDENTATION of a heading is already its
-- level; give each command its own glyph in `conceal.maps.sections` to grade them.

---@type table<string, string>
M.sections = {
    ["\\part"] = "󰉹",
    ["\\chapter"] = "󰉹",
    ["\\section"] = "󰉹",
    ["\\subsection"] = "󰉹",
    ["\\subsubsection"] = "󰉹",
    ["\\paragraph"] = "󰉹",
    ["\\subparagraph"] = "󰉹",
}

--- The shipped maps by GROUP NAME — the same keys `conceal.groups` and `conceal.maps` use, so the
--- renderer can walk groups generically instead of naming each table.
---@type table<string, table>
M.maps = {
    math_symbols = M.math_symbols,
    scripts = M.scripts,
    delimiters = M.delimiters,
    accents = M.accents,
    styles = M.styles,
    refs = M.refs,
    sections = M.sections,
}

return M
